--- # COnditional When Playbook Example
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks: 
   - name: install apache for Debian
     command: apt-get install apache2 -y
     when: ansible_os_family =="Debian"
   - name: install httpd for redhat
     command: yum install httpd -y
     when: ansible_os_family =="RedHat"
