

--- # My First yaml Playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: install HTTPS server on Centos7
            action: yum name=httpd state=installed
            notify: restart HTTPD

  handlers:
          - name: restart HTTPD
            action: service name=httpd state=restarted

